### PR TITLE
New version (dusting, bug fixes, new features)

### PR DESCRIPTION
**Pull request by melpetera**
Hi there,

I have been saying "This already is on my To-Do list" for way too long. Although I could not manage to do everything I planned in the time I could reasonably allocate to it these last months, here comes the priority part of the longing updates.

**Summary of modifications:**
- re-organisation of linear/lowess/loess ("3L") part of code to prepare eventual split of "Galaxy-linked" and "algorithm-linked" code in separate repositories
- gathering of "personalised sampleMetadata coding" parameters in a dedicated section in the interface
- several minor "bug fixes" and enhancements
- a new feature further to the update concerning NA handling (that was not dealt with previously in the 3L part): "Null values" becomes "Unconsistant values" and has now 3 options

@jfrancoismartin @ethevenot @pkrog could you please have a look? Does this sound ok for you?
I organised the commits with tags [3L], [XML], [doc] to help you check more specifically what may be of interest for you (since that is quite a few commits and all may not be of interest for everyone). 

In particular there are a few points I would like to have your opinion on:
- The test part that is available in the "test-data" folder should not change since the options used are not concerned by my modifications. However, since the test part in the **"test" folder** also concerns the 3L methods (with Determine_BC also), I expect the changes I made to slightly change the results of these tests. But since I am not familiar with the structure used in this test part, I have not change anything yet. I would need some guidance on what should be changed exactly in these files. If the person that made this part could shortly explain to me what to do with this part, I could provide the correct new results for the tests to be able to run smoothly. 
- Since there are quite a few changes for the 3L part, and given the previous changes in the interface and in the all_loess part in the previous 2.X.X versions, I suggested a **version change to 3.0.0**. Does this seem ok for you guys? 

Thank you in advance for your feedbacks!

Mélanie

### CODE REVIEW

**Comment by jfrancoismartin** [comment]
Everything is Ok for me. Thank's a lot Melanie

**Comment by melpetera** [comment]
Thank you JF for your review 😉 

@ethevenot  and @pkrog are the propositions ok for you? 
I would also need some guidance concerning the "test" folder that would need an update.

**Comment by melpetera** [comment]
As suggested by @ethevenot in private exchanges, I changed the second test in Batch correction tool's XML for it to test one of the 3L methods, that was not yet included (8a6c74f).

**Comment by melpetera** [comment]
@lecorguille 
Tests do not pass on GitHub although I had it all green testing it inside the Planemo VM. Any clues?

**Comment by melpetera** [comment]
For now, RUnit tests should not be run. A dedicated work will be investigated separately (see #21). 

Appart from the Travis CI not running properly for a reason I do not understand, this PR is ready to be merged.

**Pull request merged**
